name: ktizo
version: 0.1.0.0
homepage: https://github.com/scott-fleischman/ktizo#readme
license: BSD3
author: Author name here
maintainer: scott-fleischman@users.noreply.github.com
copyright: 2017 Scott Fleischman
category: Web
extra-source-files:
- README.md

dependencies:
  - base
  - bytestring
  - directory
  - github
  - path
  - stack
  - text
  - vector
  - yaml

executables:
  ktizo:
    source-dirs: src
    main: Main.hs
